name: "Bug Report"
description: "버그 리포트"
title: "fix(<scope>): "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        버그를 발견하셨나요? 아래 양식을 작성해주시면 빠르게 해결하겠습니다.

  - type: dropdown
    id: scope
    attributes:
      label: "Scope (영역)"
      description: "버그가 발생한 영역을 선택하세요."
      options:
        - rag
        - chat
        - agent
        - multi-agent
        - chain
        - kg (Knowledge Graph)
        - vision
        - audio
        - eval
        - optimizer
        - orchestrator
        - playground
        - cli
        - infrastructure
        - other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "버그 설명"
      description: "어떤 버그인지 간단히 설명해주세요."
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: "재현 단계"
      description: "버그를 재현하는 방법을 단계별로 작성해주세요."
      placeholder: |
        1. `Client(model="gpt-4o")`로 클라이언트 생성
        2. `client.chat([{"role": "user", "content": "Hello"}])` 호출
        3. Rate limit 에러 발생 시 재시도 없이 바로 실패
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: "기대 동작"
      description: "정상적으로 동작해야 하는 방식을 설명해주세요."
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: "실제 동작"
      description: "현재 어떻게 동작하는지 설명해주세요."
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: "Python 버전"
      placeholder: "3.11.5"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: "OS"
      placeholder: "macOS 15.2 / Ubuntu 22.04 / Windows 11"
    validations:
      required: true

  - type: input
    id: beanllm-version
    attributes:
      label: "beanllm 버전"
      placeholder: "0.3.0"
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: "에러 로그 (선택)"
      description: "관련 에러 메시지나 traceback을 붙여넣어주세요."
      render: shell
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: "추가 정보 (선택)"
      description: "스크린샷, 관련 이슈 등"
    validations:
      required: false
