name: "Feature Request"
description: "새로운 기능 요청"
title: "feat(<scope>): "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        새로운 기능을 제안해주세요. 가능한 한 구체적으로 작성해주시면 빠르게 반영할 수 있습니다.

  - type: dropdown
    id: scope
    attributes:
      label: "Scope (영역)"
      description: "기능이 속하는 영역을 선택하세요."
      options:
        - rag
        - chat
        - agent
        - multi-agent
        - chain
        - kg (Knowledge Graph)
        - vision
        - audio
        - eval
        - optimizer
        - orchestrator
        - playground
        - cli
        - infrastructure
        - other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "기능 설명"
      description: "어떤 기능이 필요한지 설명해주세요."
      placeholder: "예: HyDE (Hypothetical Document Embeddings) 기반 query expansion을 RAG 파이프라인에 추가"
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: "동기 / 목적"
      description: "이 기능이 왜 필요한지 설명해주세요. 어떤 문제를 해결하나요?"
      placeholder: "예: 현재 RAG의 retrieval 정확도가 낮아서, query expansion으로 20% 이상 개선이 가능함"
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: "제안하는 구현 방법"
      description: "어떻게 구현하면 좋을지 아이디어가 있다면 적어주세요."
      placeholder: |
        1. domain/retrieval/hyde.py에 HyDEQueryExpander 클래스 추가
        2. RAGServiceImpl에서 query expansion 단계로 통합
        3. 벤치마크 테스트 추가
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: "대안 (선택)"
      description: "고려한 다른 방법이 있다면 적어주세요."
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: "추가 정보 (선택)"
      description: "스크린샷, 참고 링크, 관련 이슈 등"
    validations:
      required: false
